name: Build and Test Functors

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/nevillegrech/gigahorse-toolchain-deps-souffle24:latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make libsoufflenum.so
    - name: Test
      run: make
    - name: Run lists_test.dl
      run: souffle lists_test.dl
    - name: Run smt-testing.dl
      run: souffle smt-testing.dl